config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :cards
  resources :user_cards

  # get "users", to: "users#index"
end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :users, :through => :user_card
	# validates :number, presence: true, uniqueness: true, length: { in: 15..16 }
	# validates :expMonth, presence: true
	# validates :expYear, numericality: { greater_than_or_equal_to: Time.now.year }
	
	# before_save :get_credit_card_type

	def get_credit_card_type
		if number.starts_with?("4")
			self.card_type = "Visa"
		elsif number.starts_with?("55")
			self.card_type = "Mastercard"
		elsif number.starts_with?("34") || number.starts_with?("37")
			self.card_type = "American Express"
		else
			self.card_type = "Other"
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cards, :through => :user_card

	validates :email, presence: true, uniqueness: { message: "Your email is not valid. Please try again." }
	validates :phone, presence: true
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :password, presence: true, length: { minimum: 8 }
	validates :balance, numericality: { greater_than_or_equal_to: 0 }
	validate :email_format_should_contain_at_symbol
	before_save :format_phone_number


	def email_format_should_contain_at_symbol
		if email.match(/@/).nil?
			errors.add(:email_format, "'#{email}' does not contain an @ symbol")
		end
	end

	def format_phone_number
		cleanup = self.phone.gsub(" ", "").gsub(".", "").gsub("-", "")
		self.phone = cleanup
	end


end

app/models/user_card.rb
class UserCard < ActiveRecord::Base
	belongs_to :user
	belongs_to :card

	validates :user_id, uniqueness: {scope: :card_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def index
		@cards = Card.all
	end

	def show
		@card = Card.find(params[:id])
		@ownership = UserCard.find_by(user_id: 1, card_id: @card.id)
	end

	def create
	end
end

app/controllers/user_cards_controller.rb
class UserCardsController < ApplicationController

	def create
		puts "UserCardsController.create() #{params}"
		result = UserCard.create(user_id: params[:user_id], card_id: params[:card_id])
		# user_id = session[:user_id]
		# card_id = params[:card][:id]

		redirect_to user_cards_path

	end

	def index
		@user_cards = UserCard.all
	end

	def destroy
		UserCard.find(params[:id]).destroy
		redirect_to user_cards_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		puts "Calling users#show with #{params[:id]}"
		@user = User.find(params[:id])
	end

	def new
		@user = User.new 
	end

	def create
		result = User.create(user_params)
		if result && !result.id.nil?
			redirect_to user_path result
		else
			flash[:alert] = result.errors.full_messages
			redirect_to "/users/new"
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	private
		def user_params
			params.require(:user).permit(:email, :phone, :first_name, :last_name, :balance, :password)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/user_cards_helper.rb
module UserCardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/index.html.erb
<h1>Cards</h1>
<% @cards.each do |card| %>

	<p>Card Number: <%= card.number %></p>
	<p>Expiration Month: <%= card.expMonth %></p>
	<p>Expiration Year: <%= card.expYear %></p>
	<p>Card Type: <%= card.card_type %></p>

	<%= link_to("Delete", card_path(card.id), method: :delete) %>
	<%= link_to("Add to my wallet", user_cards_path(card_id: card.id, user_id: session[:user_id]), method: :post) %>

	<%# link_to("Delete", card_path(@card.id), method: :delete) %>
	<%# if @ownership.nil? %>
		<%# link_to("Add to my wallet", user_cards_path(card_id: @card.id, user_id: 1), method: :post) %>
	<%# else %>
		<%# link_to("Remove from my wallet", user_card_path(card_id: @card.id, user_id: 1), method: :delete) %>
	<%# end %>
	<hr>

<% end %>

app/views/cards/show.html.erb
<div class="card">
	<p>Card Number: <%= @card.number %></p>
	<p>Card Expiration Month: <%= @card.expMonth %></p>
	<p>Card Expiration Year: <%= @card.expYear %></p>
	<p>Card Type: <%= @card.card_type %></p>

	<% link_to("Delete", card_path(@card.id), method: :delete) %>
	<% if @ownership.nil? %>
		<% link_to("Add to my wallet", user_cards_path(card_id: @card.id, user_id: 1), method: :post) %>
	<% else %>
		<% link_to("Remove from my wallet", user_card_path(card_id: @card.id, user_id: 1), method: :delete) %>
	<% end %>

</div>

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyWalletApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
		<%#= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	<% end %>

	<%= yield %>
	<ul class="footer-links">
		<li><%= link_to "Users", users_path %></li>
		<li><%= link_to "Cards", cards_path %></li>
		<li><%= link_to "User Cards", user_cards_path %></li>
	</ul>

</body>
</html>

app/views/user_cards/index.html.erb
<% @user_cards.each do |uc| %>
	<%= link_to(uc.user.first_name, user_path(uc.user.id)) %> <%= link_to(uc.card.number, card_path(uc.user.id)) %>
	<p>
		<%= uc.user.first_name %> <%=uc.user.last_name %> can use <%= uc.card.card_type %> for online shopping!
	</p>
	<hr>

<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<h4><%= user.first_name %> <%= user.last_name %></h4>
	<hr>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |u| %>
	<%= u.label :email %>
	<%= u.text_field :email %><br>
	<%= u.label :phone %>
	<%= u.text_field :phone %><br>
	<%= u.label :first_name %>
	<%= u.text_field :first_name %><br>
	<%= u.label :last_name %>
	<%= u.text_field :last_name %><br>
	<%= u.label :balance %>
	<%= u.text_field :balance %><br>
	<%= u.label :password %>
	<%= u.text_field :password %><br>

	<%= u.submit :create %>

<% end %>

app/views/users/show.html.erb
<%= @user.first_name %> <%= @user.last_name %>